services:

  # storage:
  #   container_name: storage-container
  #   image: redis:7.0
  #   volumes:
  #     - ./data:/data 

  # counter:
  #   container_name: counter-container
  #   build: ./counter
  #   ports:
  #     - 4001:3001
  #   environment:
  #     - PORT=3001
  #     - REDIS_URL=redis://storage
  #   depends_on:
  #     - storage

  mongo:
    container_name: database-container
    image: mongo
    volumes:
      - ./data/mongo:/data/db 
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    container_name: admin-panel-container
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  library:
    container_name: library-container
    build: ./library
    ports:
      - 4002:3002
    environment:
      - PORT=3002
      - COUNTER_URL=http://counter:3001
      - MONGODB_URL=mongodb://mongo:27017
      - MONGODB_LOGIN=root
      - MONGODB_PASSWORD=example
      - DB_NAME=library
    volumes:
    # А вот это вторая составляющая разработки без перезапуска контейнера. Надо ее оставлять в композ-дев. В продакшн-композ это тащить не надо
      - ./library/src:/app/src
    depends_on:
      # - counter
      - mongo
      - mongo-express
