services:

  storage:
    container_name: redis-storage-container
    image: redis:7.0
    volumes:
      - ./data/redis:/data

  counter:
    container_name: counter-container
    build: ./counter
    ports:
      - 4001:3001
    environment:
      - PORT=3001
      - REDIS_URL=$REDIS_URL
    depends_on:
      - storage

  # Тут нигде не сказано, но монга доступна вот на этом порту: 27017 (внешнем или внутреннем?)
  mongo:
    container_name: mongo-database-container
    image: mongo
    volumes:
      - ./data/mongo:/data/db
    restart: always
    # ports:
    #   - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_LOGIN
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD

  mongo-express:
    container_name: mongo-admin-panel-container
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_LOGIN
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: $MONGO://$MONGO_LOGIN:$MONGO_PASSWORD@$MONGO_SERVICE_NAME:$MONGO_SERVICE_PORT/
    depends_on:
      - mongo

  library:
    container_name: library-container
    build: ./library
    ports:
      - 4002:3002
    env_file: .env
    environment:
      - PORT=3002
      - COUNTER_URL=$COUNTER_URL
      - MONGODB_URL=$MONGODB_URL
      - MONGODB_LOGIN=$MONGO_LOGIN
      - MONGODB_PASSWORD=$MONGO_PASSWORD
      - DB_NAME=$MONGO_DB_NAME
    volumes:
      # А вот это вторая составляющая разработки без перезапуска контейнера. Надо ее оставлять в композ-дев. В продакшн-композ это тащить не надо
      - ./library/src:/app/src
    depends_on:
      - counter
      - mongo
      - mongo-express

# Как имя сервиса напрямую задать чтобы он их не склеивал, когда создает образ?
# Секции именованного вольма и нетворк
# Зачем докер-игнор?